version: "3.9"

services:
  nginx:
    image: {{ env.NGINX_IMAGE }}
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      NGINX_CERT: {{ env.NGINX_CERT }}
      NGINX_CERT_KEY: {{ env.NGINX_CERT_KEY }}
    depends_on:
      - server
      - pgadmin
    networks:
      - awesome

  server:
    image: {{ env.APP_IMAGE }}
    restart: always
    ports:
        - "{{ env.SERVER_PORT }}:{{ env.SERVER_PORT }}"
    environment:
      SERVER_PORT: {{ env.SERVER_PORT }}
      POSTGRES_PORT: {{ env.POSTGRES_PORT }}
      POSTGRES_PASSWORD: {{ env.POSTGRES_PASSWORD }}
      POSTGRES_USER: {{ env.POSTGRES_USER }}
      POSTGRES_DB: {{ env.POSTGRES_DB }}
    depends_on:
      - postgres
    networks:
      - awesome

  postgres:
    image: postgres:14
    ports:
      - "{{ env.POSTGRES_PORT }}:{{ env.POSTGRES_PORT }}"
    environment:
      POSTGRES_PASSWORD: {{ env.POSTGRES_PASSWORD }}
      POSTGRES_USER: {{ env.POSTGRES_USER }}
      POSTGRES_DB: {{ env.POSTGRES_DB }}
    volumes:
      - /tmp/pgdata:/var/lib/postgresql/data
    networks:
      - awesome

  pgadmin:
    user: root
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - /tmp/pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - awesome

networks:
  awesome:
    driver: bridge
